((emacs-lisp-mode . ((fill-column . 100)
                     (indent-tabs-mode . nil)
                     (elisp-lint-ignored-validators . ("byte-compile" "package-lint" "fill-column"))
                     (elisp-lint-indent-specs . ((describe . 2)
                                                 (it . 2))))))
