#+TITLE: Obsidian Notes for Emacs

During the development of Obsidian.el I have learned and copied from the code of the amazing [[https://github.com/org-roam/org-roam][org-roam]] package. Thank you!

The purpose is to make an Obsidian Notes comfortably writable in Emacs. Obviously you already can open your Obsidian folder and start creating markdown files with Emacs. Let's try to improve that a little.

* What does Obsidian.el do?
- [ ] Autocomplete Obsidian tags
- [ ] Autocomplete Obsidian file links

* Development tasks
** TODO General utils
- [X] Specify Obsidian folder and save it in variables
- [ ] Enumerate files in the Obsidian folder and save a list
- [ ] Run the enumeration task in the background
- [ ] Functions to scan notes for tags
- [ ] Functions to scan notes for links
- [ ] Capture command to create a new note in Obsidian folder
- [ ] Database (?) for the scan results

** TODO Autocompletion for tags
** TODO Autocompletion for note links

* Install
Using use-package and straight.el:

#+begin_src elisp
  (use-package obsidian
    :straight (:type git :host github :repo "licht1stein/obsidian.el")
    :confg (obsidian-specify-path "~/MY_OBSIDIAN_FOLDER"))
#+end_src
