#+TITLE: Obsidian Notes for Emacs
Emacs front-end for [[https://obsidian.md/][Obsidian Notes]].

* Install
Using [[https://github.com/jwiegley/use-package][use-package]] and [[https://github.com/radian-software/straight.el][straight.el]]:

#+begin_src elisp
  (use-package obsidian
    :straight (:type git :host github :repo "licht1stein/obsidian.el")
    :config (obsidian-specify-path "~/MY_OBSIDIAN_FOLDER"))
#+end_src

* About Obsidian.el

I wanted to work with Obsidian Notes using Emacs. Obviously you already can open your Obsidian folder and start editing markdown files with Emacs. But I want to improve that and split the responsibilities between Emacs and Obsidian the way it makes sense for an Emacs user.

** What should we keep doing in Obsidian?
- Sync
- Mobile client (of course, and that's where Obsidian beats anything else in Emacs)
- Complex exploring (graph views etc)
- All the things done with complex plugins

** What should be possible to do in Emacs?
Obsidian.el must empower us to stay in Emacs for things that make sense in Emacs:

- [ ] Creating and editing notes with convenient autocomplete for tags and links (nothing will ever compare to Emacs in terms of editing power)
- [ ] Jumping between notes
- [ ] Searching all notes
- [ ] Viewing and following backlinks

When all of the above is ready we will almost never need the Obsidian app on desktop, but will still be able to use it on mobile or when specifically needed.

*** Development tasks
- [X] Specify Obsidian folder and save it in variables
- [X] Enumerate files in the Obsidian folder and save a list
- [ ] Run the enumeration task in the background (or trigger it when viewing an Obsidian file)
- [X] Functions to scan notes for tags
- [X] Get full list of all tags
- [X] company-backend with tags
- [ ] Functions to scan notes for links
- [ ] Capture command to create a new note in Obsidian folder
- [ ] Database (?) for the scan results
- [X] Obsidian minor for matching .md files

* Why not?
** Obsidian App, Athens Research or any other great app?
Easy. They are not Emacs. You could probably use some of them as the back-end for a similar set up, but I happen to prefer Obsidian.

** Org-roam or any other great Emacs libraries?
The answer is mostly the same for all of them. Mobile. And when choosing what to build — a mobile app for org-roam or an Emacs client for Obsidian, I prefer the latter. A much, much simpler task.

* Gratitude
- The work on Obsidian.el was made considerably easier and definitely more fun thanks to the great work of [[https://github.com/magnars][Magnar Sveen]] and his packages [[https://github.com/magnars/dash.el][dash.el]] and [[https://github.com/magnars/s.el][s.el]]. Thank you for making Elisp almost as convenient as Clojure!

- During the development of Obsidian.el I have learned and copied from the code of the amazing [[https://github.com/org-roam/org-roam][org-roam]] package. Thank you!
