#+TITLE: Obsidian Notes for Emacs
Emacs front-end for [[https://obsidian.md/][Obsidian Notes]].

This package is still work in progress, but I think it's ready enough to be used by those who want to use it.

* Install
Using [[https://github.com/jwiegley/use-package][use-package]] and [[https://github.com/radian-software/straight.el][straight.el]]:

#+begin_src elisp
  (use-package obsidian
    :straight (:type git :host github :repo "licht1stein/obsidian.el")
    :config (obsidian-specify-path "~/MY_OBSIDIAN_FOLDER")
    :custom
    (obsidian-inbox-directory "Inbox"))
#+end_src

Optionally you can specify ~obsidian-inbox-directory~, it will be used by ~obsidian-capture~ to store new notes into. If you don't set it the root folder of your Obsidian vault will be used.

* About Obsidian.el

I wanted to work with Obsidian Notes using Emacs. Obviously you already can open your Obsidian folder and start editing markdown files with Emacs. But I want to improve that and split the responsibilities between Emacs and Obsidian the way it makes sense for an Emacs user.

** What should we keep doing in Obsidian?
- Sync
- Mobile client (of course, and that's where Obsidian beats anything else in Emacs)
- Complex exploring (graph views etc)
- All the things done with complex plugins

** What should be possible to do in Emacs?
Obsidian.el must empower us to stay in Emacs for things that make sense in Emacs:

- [X] Creating and editing notes with convenient autocomplete for tags and links (nothing will ever compare to Emacs in terms of editing power)
- [X] Jumping between notes
- [ ] Searching all notes
- [ ] Viewing and following backlinks

When all of the above is ready we will almost never need the Obsidian app on desktop, but will still be able to use it on mobile or when specifically needed.

* How does obsidian.el work?
** obsidian-mode
When you require obsidian.el via ~use-package~ or in other ways (see snippet above), you have to specify the root folder of your Obsidian Notes vault. Once obsidian.el knows the root folder, each time you open a markdown buffer it checks, if that file is part of your Obsidian Notes vault. If it is ~obsidian-mode~ minor mode is activated for this buffer.

** company-mode completion
Once the ~obsidian-mode~ is activated obsidian.el scans all markdown files in the vault for tags and links (links still WIP), and stores these lists in it's global variables. It also adds [[http://company-mode.github.io/][company-mode]] backends to suggest links and tags for completion.

** Manual re-scan
You can update the lists of tags, links etc. manually if it's lagging for some reason by running an interactive command:

#+begin_src
  M-x obsidian-update RET
#+end_src

** Inserting links
There are two commands to insert links ~obsidian-insert-link~ and ~obsidian-insert-wikilink~, you can choose one depending on your preferred link format:

*** Inserts a link in Markdown format
Example: ~[Link description](path/to/file.md)~
#+begin_src
  M-x obsidian-insert-link RET
#+end_src

*** Insert a link in wikilink format
Example: ~[[path/fo/file.md|Link description]]~

#+begin_src
  M-x obsidian-insert-wikilink RET
#+end_src

** Jumping between notes
Quickly jump between notes using ~obsidian-jump~

#+begin_src
  M-x obsidian-jump RET
#+end_src

** Capturing new note
Use ~obsidian-capture~. If you specified ~obsidian-inbox-directory~, it will create new notes in this directory. Otherwise in your Obsidian vault root directory:

#+begin_src
  M-x obsidian-capture RET
#+end_src

*** Development tasks
- [X] Specify Obsidian folder and save it in variables
- [X] Enumerate files in the Obsidian folder and save a list
- [X] Run the scan when entering obsidian-mode
- [X] Functions to scan notes for tags
- [X] Get full list of all tags
- [X] company-backend with tags
- [X] commands to insert links in markdown and wikilink
- [X] Capture command to create a new note in Obsidian folder
- [X] Obsidian minor for matching .md files
- [X] Jumping between notes
- [ ] Functions to scan notes for links

* Why obsidian.el and not...
** Obsidian App itself, Athens Research or any other great app?
Easy. When on desktop they are simply not Emacs.  Not even Obsidian itself. Emacs beats anything else for things that it is built for. But you know this already, otherwise you wouldn't be here.

** Org-roam or any other great Emacs libraries?
The answer is mostly the same for all of them. Mobile support. Or rather — NO mobile support. I don't buy into the story that "you don't really need your PKM system on mobile", and "serious work is done only on desktop" etc. These are just excuses for the impossibility of building a full-fledged mobile version of Emacs.

So there were two ways to go about it: build a mobile app for something like org-roam (which would be cool, but is above my front-end skills) or build a light-weight Emacs client for something like Obsidian. I chose the simpler task.

* Gratitude
- The work on Obsidian.el was made considerably easier and definitely more fun thanks to the great work of [[https://github.com/magnars][Magnar Sveen]] and his packages [[https://github.com/magnars/dash.el][dash.el]] and [[https://github.com/magnars/s.el][s.el]]. Thank you for making Elisp almost as convenient as Clojure!

- During the development of Obsidian.el I have learned and copied from the code of the amazing [[https://github.com/org-roam/org-roam][org-roam]] package. Thank you!
